[workspace]
# List of crates included in this workspace
members = [ "arbiter-bindings", "arbiter-core", "arbiter-derive", "arbiter-engine"]

# List of crates excluded from this workspace
exclude = ["benches"]

# Package configuration
[package]
name = "arbiter"
version = "0.4.13"
edition = "2021"
authors = ["Waylon Jepsen <waylonjepsen1@gmail.com>", "Colin Roberts <colin@autoparallel.xyz>"]
description = "Allowing smart contract developers to do simulation driven development via an EVM emulator"
license = "Apache-2.0"
keywords = ["ethereum", "evm", "emulator", "testing", "smart-contracts"]

# Binary configuration
[[bin]]
name = "arbiter"
path = "bin/main.rs"

[workspace.dependencies]
ethers = { version = "=2.0.11" }
serde = { version = "=1.0.192", features = ["derive"] }
serde_json = { version = "=1.0.108" }
revm = { git = "https://github.com/bluealloy/revm", branch = "reth_freeze",  features = ["std", "secp256k1", "ethersdb", "serde"], default-features = false }
revm-primitives = { git = "https://github.com/bluealloy/revm", branch = "reth_freeze", features = ["std"], default-features = false }
thiserror = { version = "=1.0.50" }
syn = { version = "=2.0.39" }
quote = { version = "=1.0.33" }
proc-macro2 = { version = "=1.0.69" }
tokio = { version = "1.34.0", features = ["macros", "full"] }
arbiter-core = { path = "./arbiter-core" }
crossbeam-channel =  { version = "=0.5.8" }
futures-util =  { version = "=0.3.29" }
async-trait =  { version = "0.1.74" }

# Dependencies for the release build
[dependencies]
arbiter-core.workspace = true

# Command line and config
clap = { version = "=4.4.11", features = ["derive"] }
serde.workspace = true
serde_json.workspace = true
config = { version = "=0.13.4" }
ethers.workspace = true
revm.workspace = true
toml = { version = "=0.8.8" }
proc-macro2.workspace = true
syn.workspace = true
Inflector = { version = "=0.11.4" }

# Building files
quote.workspace = true
foundry-config = { version = "=0.2.0" }
tempfile = { version = "3.8.1"}

# Errors
thiserror.workspace = true

# Dependencies for the test build and development
[dev-dependencies]
tokio.workspace = true
assert_cmd = { version = "=2.0.12" }
rayon = { version = "1.8.0" }
revm-primitives.workspace = true

# Release profile
[profile.release]
# Link-Time Optimization can improve runtime at cost of build time
lto = true
# The Rust compiler splits your crate into multiple codegen units to parallelize (and thus speed up) compilation but at the cost of optimization. 
# This setting tells the compiler to use only one codegen unit, which will slow down compilation but improve optimization.
codegen-units = 1


